### ISSUE TITLE
QHelpEngine: No such file or directory

### ISSUE THREAD

**Issue by lorenzleutgeb** [uglyDwarf/linuxtrack#155]
Attempting to build on Fedora 30 with Qt 4.8.7 and  5.12.1:

```
$ make
...
Project MESSAGE: Warning: unknown QT: help
...
../qt_gui/help_view.cpp:8:10: fatal error: QHelpEngine: No such file or directory
    8 | #include <QHelpEngine>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:378: help_view.o] Error 1
```

I don't get `ltr_gui`.

**Comment by alexolivan** [comment]
Hi.
Yep ... Exact same thing on Debian Buster.

Hope this could be fixed...

**Comment by hyarion** [comment]
I had the same issue on centos7. I fixed it by using qt5 instead:

1. $ sudo yum install qt5-qttools-devel
2. in [configure.ac +46](https://github.com/uglyDwarf/linuxtrack/blob/master/configure.ac#L46), add change `qmake qmake-qt4` to `qmake qmake-qt5 qmake-qt4`
3. $ autoreconf -i configure.ac
4. $ ./configure
5. $ make

**Comment by alexolivan** [comment]
Thanks. That worked!

Also, I replaced opencv to opencv4 at line 216 to get Debian packagedp libopencv-dev to get detected.

Regards
